apiVersion: v1
kind: Service
metadata:
  name: shopping-list
  namespace: woodpantry
  labels:
    app: shopping-list
spec:
  selector:
    app: shopping-list
  ports:
    - port: 80
      targetPort: 8080
