// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type ShoppingList struct {
	ID         uuid.UUID
	RecipeIds  []uuid.UUID
	MealPlanID uuid.NullUUID
	CreatedAt  time.Time
}

type ShoppingListItem struct {
	ID               uuid.UUID
	ShoppingListID   uuid.UUID
	IngredientID     uuid.UUID
	Name             string
	Category         string
	QuantityNeeded   float64
	QuantityInPantry float64
	QuantityToBuy    float64
	Unit             string
	CreatedAt        time.Time
}
