// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateShoppingList(ctx context.Context, arg CreateShoppingListParams) (ShoppingList, error)
	CreateShoppingListItem(ctx context.Context, arg CreateShoppingListItemParams) (ShoppingListItem, error)
	GetShoppingList(ctx context.Context, id uuid.UUID) (ShoppingList, error)
	ListShoppingListItems(ctx context.Context, shoppingListID uuid.UUID) ([]ShoppingListItem, error)
}

var _ Querier = (*Queries)(nil)
