// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shopping_lists.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createShoppingList = `-- name: CreateShoppingList :one
INSERT INTO shopping_lists (
    id,
    recipe_ids,
    meal_plan_id
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, recipe_ids, meal_plan_id, created_at
`

type CreateShoppingListParams struct {
	ID         uuid.UUID
	RecipeIds  []uuid.UUID
	MealPlanID uuid.NullUUID
}

func (q *Queries) CreateShoppingList(ctx context.Context, arg CreateShoppingListParams) (ShoppingList, error) {
	row := q.db.QueryRowContext(ctx, createShoppingList, arg.ID, pq.Array(arg.RecipeIds), arg.MealPlanID)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		pq.Array(&i.RecipeIds),
		&i.MealPlanID,
		&i.CreatedAt,
	)
	return i, err
}

const createShoppingListItem = `-- name: CreateShoppingListItem :one
INSERT INTO shopping_list_items (
    id,
    shopping_list_id,
    ingredient_id,
    name,
    category,
    quantity_needed,
    quantity_in_pantry,
    quantity_to_buy,
    unit
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, shopping_list_id, ingredient_id, name, category, quantity_needed, quantity_in_pantry, quantity_to_buy, unit, created_at
`

type CreateShoppingListItemParams struct {
	ID               uuid.UUID
	ShoppingListID   uuid.UUID
	IngredientID     uuid.UUID
	Name             string
	Category         string
	QuantityNeeded   float64
	QuantityInPantry float64
	QuantityToBuy    float64
	Unit             string
}

func (q *Queries) CreateShoppingListItem(ctx context.Context, arg CreateShoppingListItemParams) (ShoppingListItem, error) {
	row := q.db.QueryRowContext(ctx, createShoppingListItem,
		arg.ID,
		arg.ShoppingListID,
		arg.IngredientID,
		arg.Name,
		arg.Category,
		arg.QuantityNeeded,
		arg.QuantityInPantry,
		arg.QuantityToBuy,
		arg.Unit,
	)
	var i ShoppingListItem
	err := row.Scan(
		&i.ID,
		&i.ShoppingListID,
		&i.IngredientID,
		&i.Name,
		&i.Category,
		&i.QuantityNeeded,
		&i.QuantityInPantry,
		&i.QuantityToBuy,
		&i.Unit,
		&i.CreatedAt,
	)
	return i, err
}

const getShoppingList = `-- name: GetShoppingList :one
SELECT id, recipe_ids, meal_plan_id, created_at
FROM shopping_lists
WHERE id = $1
`

func (q *Queries) GetShoppingList(ctx context.Context, id uuid.UUID) (ShoppingList, error) {
	row := q.db.QueryRowContext(ctx, getShoppingList, id)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		pq.Array(&i.RecipeIds),
		&i.MealPlanID,
		&i.CreatedAt,
	)
	return i, err
}

const listShoppingListItems = `-- name: ListShoppingListItems :many
SELECT id, shopping_list_id, ingredient_id, name, category, quantity_needed, quantity_in_pantry, quantity_to_buy, unit, created_at
FROM shopping_list_items
WHERE shopping_list_id = $1
ORDER BY category, name, created_at, id
`

func (q *Queries) ListShoppingListItems(ctx context.Context, shoppingListID uuid.UUID) ([]ShoppingListItem, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingListItems, shoppingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingListItem
	for rows.Next() {
		var i ShoppingListItem
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingListID,
			&i.IngredientID,
			&i.Name,
			&i.Category,
			&i.QuantityNeeded,
			&i.QuantityInPantry,
			&i.QuantityToBuy,
			&i.Unit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
